import React, { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PageHeader } from '@/components/shared/PageHeader';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { alumniApi, type AlumniEmployment, type EmploymentSector } from '../api/alumniApi';
import { useAuth } from '@/contexts/AuthContext';

const blank = (): Omit<AlumniEmployment, 'id' | 'alumni_id' | 'created_at' | 'updated_at'> => ({ organization: '', position: '', sector: 'industry', city: '', country: '', start_date: null, end_date: null, is_current: false });
export default function AlumniEditPage() {
  const qc = useQueryClient();
  const { user } = useAuth();
  const profile = useQuery({ queryKey: ['alumni', 'me'], queryFn: async () => (await alumniApi.getMyProfile()).data, retry: false });
  const jobs = useQuery({ queryKey: ['alumni', 'my-employments'], queryFn: async () => (await alumniApi.myEmployments()).data, retry: false });
  const [form, setForm] = useState({ current_city: '', current_country: '', bio: '', phone: '', email_visible: false, phone_visible: false });
  const [employments, setEmployments] = useState<ReturnType<typeof blank>[]>([]);
  useEffect(() => { if (profile.data) setForm({ current_city: profile.data.current_city ?? '', current_country: profile.data.current_country ?? '', bio: profile.data.bio ?? '', phone: profile.data.phone ?? '', email_visible: profile.data.email_visible ?? false, phone_visible: profile.data.phone_visible ?? false }); }, [profile.data]);
  useEffect(() => { if (jobs.data) setEmployments(jobs.data.map((job) => ({ organization: job.organization, position: job.position, sector: job.sector, city: job.city, country: job.country, start_date: job.start_date, end_date: job.end_date, is_current: job.is_current }))); }, [jobs.data]);
  const saveProfile = useMutation({ mutationFn: () => alumniApi.updateMyProfile(form), onSuccess: () => qc.invalidateQueries({ queryKey: ['alumni', 'me'] }) });
  const saveJobs = useMutation({ mutationFn: () => alumniApi.replaceMyEmployments(employments), onSuccess: () => qc.invalidateQueries({ queryKey: ['alumni', 'my-employments'] }) });
  const updateJob = (index: number, key: keyof ReturnType<typeof blank>, value: string | boolean | null) => setEmployments((old) => old.map((job, item) => item === index ? { ...job, [key]: value } : job));
  return <div className="space-y-6">
    <PageHeader kicker="Your alumni profile" title="Keep your journey current" description={`Signed in as ${user?.full_name ?? 'alumni'}. Changes are limited to your own profile.`} />
    {profile.isError && <p role="alert" className="rounded-xl border border-[var(--danger)] bg-[var(--danger-soft)] p-4 text-sm text-[var(--danger)]">Create or claim an alumni profile before editing it.</p>}
    <section className="surface space-y-4 p-5"><p className="kicker">Profile and privacy</p><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs text-[var(--text-subtle)]">Current city<Input value={form.current_city} onChange={(event) => setForm({ ...form, current_city: event.target.value })} /></label><label className="text-xs text-[var(--text-subtle)]">Current country<Input value={form.current_country} onChange={(event) => setForm({ ...form, current_country: event.target.value })} /></label><label className="text-xs text-[var(--text-subtle)] sm:col-span-2">Phone<Input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label className="text-xs text-[var(--text-subtle)] sm:col-span-2">Bio<textarea className="mt-1 min-h-28 w-full rounded-lg border border-[var(--border)] bg-[var(--bg-elevated)] p-3 text-sm text-[var(--text)]" value={form.bio} onChange={(event) => setForm({ ...form, bio: event.target.value })} /></label></div><div className="space-y-2 text-sm text-[var(--text-muted)]"><label className="flex items-center gap-2"><input type="checkbox" checked={form.email_visible} onChange={(event) => setForm({ ...form, email_visible: event.target.checked })} /> Show my email to logged-in portal users</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.phone_visible} onChange={(event) => setForm({ ...form, phone_visible: event.target.checked })} /> Show my phone to logged-in portal users</label></div><Button onClick={() => saveProfile.mutate()} disabled={saveProfile.isPending || !profile.data}>{saveProfile.isPending ? 'Saving…' : 'Save profile'}</Button></section>
    <section className="surface space-y-4 p-5"><div className="flex items-center justify-between gap-3"><div><p className="kicker">Career timeline</p><p className="mt-1 text-sm text-[var(--text-muted)]">Keep one current role at most; past roles can remain visible.</p></div><Button size="sm" variant="outline" onClick={() => setEmployments([...employments, blank()])}>Add role</Button></div>{employments.map((job, index) => <div key={index} className="grid gap-3 rounded-lg border border-[var(--border)] p-4 sm:grid-cols-2"><label className="text-xs text-[var(--text-subtle)]">Organization<Input value={job.organization} onChange={(event) => updateJob(index, 'organization', event.target.value)} /></label><label className="text-xs text-[var(--text-subtle)]">Position<Input value={job.position} onChange={(event) => updateJob(index, 'position', event.target.value)} /></label><label className="text-xs text-[var(--text-subtle)]">Sector<select className="mt-1 h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--bg-elevated)] px-3 text-sm" value={job.sector} onChange={(event) => updateJob(index, 'sector', event.target.value as EmploymentSector)}>{['industry', 'academia', 'government', 'startup', 'higher_study', 'other'].map((value) => <option key={value} value={value}>{value.replace('_', ' ')}</option>)}</select></label><label className="text-xs text-[var(--text-subtle)]">Country<Input value={job.country ?? ''} onChange={(event) => updateJob(index, 'country', event.target.value)} /></label><label className="text-xs text-[var(--text-subtle)]">Start date<Input type="date" value={job.start_date ?? ''} onChange={(event) => updateJob(index, 'start_date', event.target.value || null)} /></label><label className="text-xs text-[var(--text-subtle)]">End date<Input type="date" value={job.end_date ?? ''} disabled={job.is_current} onChange={(event) => updateJob(index, 'end_date', event.target.value || null)} /></label><label className="flex items-center gap-2 text-sm text-[var(--text-muted)]"><input type="checkbox" checked={job.is_current} onChange={(event) => updateJob(index, 'is_current', event.target.checked)} /> Current role</label><Button type="button" size="sm" variant="outline" onClick={() => setEmployments(employments.filter((_, item) => item !== index))}>Remove</Button></div>)}<Button onClick={() => saveJobs.mutate()} disabled={saveJobs.isPending}>{saveJobs.isPending ? 'Saving…' : 'Save career timeline'}</Button></section>
  </div>;
}
